module Services.Translate.Keys exposing (TranslationKey(..))


type TranslationKey
    = Welcome
    | Error404
    | Home
    | Home_Title
    | Home_Subtitle
    | Home_Description
    | Features_Editor
    | Features_Editor_Desc
    | Features_Groups
    | Features_Groups_Desc
    | Features_Votes
    | Features_Votes_Desc
    | Use_Cases_Company
    | Use_Cases_Company_Desc
    | Use_Cases_Politics
    | Use_Cases_Politics_Desc
    | Use_Cases_Groups
    | Use_Cases_Groups_Desc
    | Log_in
    | Log_out
    | Create_Account
    | Password
    | Email
    | Issues
    | Documentation
    | Repository
    | Features
    | Use_Cases
    | Developers
    | Add
    | Explore
    | Group_add
    | Text_add
    | Groups_List
    | Texts_List
    | Votes_List
    | Add_Amend
    | Show_Text
    | Show_Group
    | Followed_Texts
    | Followed_Groups
    | HomeTitle
    | SignInTitle
    | SignUpTitle
    | ProfileTitle
    | NotFoundTitle